### ISSUE TITLE
will code be open source?

### ISSUE THREAD

**Issue by HaoBytes** [THU-BPM/HiURE#1]
Hi, I saw this good paper and want to reproduce it.

May I ask whether this paper's code will be open source later?

**Comment by MichaelLyo** [comment]
Thanks for the kind reminder.
We have released the source code.

**Comment by bianchixr4** [comment]
> 嗨，我看到了这篇好论文，想复制它。
> 
> 请问本文的代码以后会开源吗？



> Hi, I saw this good paper and want to reproduce it.
> 
> May I ask whether this paper's code will be open source later?

Hi, may I ask if you have reproduced the relevant indicators in the paper？

**Comment by gxxxzhang** [comment]
> Hi, I saw this good paper and want to reproduce it.
> 
> May I ask whether this paper's code will be open source later?

Hi, may I ask if you have reproduced the relevant indicators in the paper？
